# Generated by Django 4.2.3 on 2023-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='учится'),
        ),
    ]
