# Generated by Django 4.2.3 on 2023-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subject_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='email'),
        ),
    ]
