# Generated by Django 4.2.3 on 2023-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subject_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='email',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='email'),
        ),
    ]
